---
dependency:
  name: galaxy
  enabled: false
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: debian13
    image: mrlesmithjr/debian:13
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
    prepare: ../shared/prepare.yml
    verify: ../shared/verify-debian-based.yml
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..
verifier:
  name: ansible
