---
name: Molecule Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        molecule_distro:
          - centos7
          - centos8
          - debian9
          - debian10
          - debian11
          - debian12
          # - fedora
          - ubuntu1804
          - ubuntu2004
          - ubuntu2204
          - ubuntu2404

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pip-tools
          pip-sync requirements.txt requirements-dev.txt
          ansible --version
          molecule --version
      - name: Test with molecule
        run: |
          molecule test --scenario-name ${{ matrix.molecule_distro }}
