---
name: Molecule Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        molecule_distro:
          - debian11
          - debian12
          - debian13
          - ubuntu2204
          - ubuntu2404

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip pip-tools
          pip-sync requirements.txt requirements-dev.txt
          ansible --version
          molecule --version
      - name: Test with molecule
        run: |
          molecule test --scenario-name ${{ matrix.molecule_distro }}
